version: '3.3'

services:
  node:
    build:
      context: ./node
      args:
        - NODE_VERSION=latest
        - PROJECT_PATH=/opt/app/
        - NODE_ENV=develop
        - YARN=false
    volumes:
      - ../:/opt/app
    entrypoint: run-nodock "npm start"
    tty: true

  nginx:
    build:
      context: ./nginx
      args:
        - WEB_REVERSE_PROXY_PORT=3012
        - WEB_SSL=false
        - SELF_SIGNED=false
        - NO_DEFAULT=false
    volumes:
      - ./data/logs/nginx/:/var/log/nginx
      - ./certbot/certs/:/var/certs
    ports:
      - '80:80'
      - '443:443'
    tty: true

  certbot:
    build:
      context: ./certbot
    links:
      - nginx
    volumes:
      - ./certbot/letsencrypt/:/var/www/letsencrypt
      - ./certbot/certs/:/var/certs
    environment:
      - CN=new.nevatrip.ru
      - EMAIL=info@nevatrip.ru
